---
layout: default
lang: el
title:  "Τα οφέλη της ΓΙΟΓΚΑ στο ΠΟΔΟΣΦΑΙΡΟ"
date:   2011-06-02 00:00:00
categories:
    - blog
---

== Τα οφέλη της ΓΙΟΓΚΑ στο ΠΟΔΟΣΦΑΙΡΟ


Στην *Ελλάδα* σήμερα, _ακούμε_ πολλές αντιφατικές γνώμες σε σχέση με την επιστήμη της γιόγκα, καθώς και πολλές θεωρίες για το τι ακριβώς είναι. Δυστυχώς πολλοί από αυτούς που πληροφορούν το κοινό δεν έχουν μελετήσει ή εφαρμόσει το σύστημα οι ίδιοι, οι αντιλήψεις τους επομένως, δεν στηρίζονται σε τεκμηριωμένα γεγονότα και οι πληροφορίες τους είναι παραπλανητικές.

Τα παραδοσιακά συστήματα, η hatha yoga και η ashtanga yoga (και σε καμία περίπτωση, οι δυτικού τρόπου παραλλαγές τους π.χ. power yoga), σαν στόχο έχουν τη βελτίωση της υγείας, σε όλα τα συστήματα του ανθρώπινου οργανισμού, μέσω σωματικών ασκήσεων, της αύξησης της ζωτικής ικανότητας των πνευμόνων, μέσω αναπνευστικών τεχνικών και τη δυνατότητα αυτοσυγκέντρωσης και ελέγχου του νου, μέσω της βαθιάς χαλάρωσης και του διαλογισμού. Με δύο λόγια σωματική και ψυχική υγεία με μεθόδους συνειδητού ελέγχου και όχι βιασμού.

Στην Ευρώπη, την Αμερική, την Αυστραλία και την Ασία η γιόγκα πλέον αποτελεί αναπόσπαστο κομμάτι του υψηλού επιπέδου αθλητισμού. Οι αθλητές των Ολυμπιακών ομάδων χρησιμοποιούν ασκήσεις γιόγκα πριν και μετά την άθλησή τους.

Οι αθλητές που κάνουν γιόγκα:

- Είναι πιο ανθεκτικοί στο στρες (GAERTNER 1965)
- Η καρδιά τους λειτουργεί πιο αποτελεσματικά(ORNISH 1983)
- Έχουν μειωμένη πίεση του αίματος
- Τα εγκεφαλικά τους κύματα δείχνουν μια πιο ήρεμη κατάσταση (ANAND & CHINA 1961, BLACKNELL 1975, FENWICK 1977)
Πολλές ποδοσφαιρικές ομάδες έχουν εντάξει στο πρόγραμμά τους μαθήματα γιόγκα. Τι μπορεί όμως συγκεκριμένα να προσφέρει σε έναν ποδοσφαιριστή το σύστημα αυτό;

Αύξηση φυσικής αντοχής

μέσω της εκγύμνασης των πνευμόνων

Οι αναπνευστικές ασκήσεις δίνουν την πλήρη πρόσληψη οξυγόνου και χρησιμοποίησή του, σύμφωνα με τις ικανότητές μας. Έτσι τα  κύτταρα οξυγονώνονται καλύτερα, με αποτέλεσμα περισσότερη υγεία στα κύτταρα και τους ιστούς, στα όργανα και τα συστήματα, σ’ ολόκληρο τον οργανισμό. Πάνω απ’ όλα αυτά  αυξάνεται η ζωτική ικανότητα του ατόμου. Σύμφωνα με επιστημονικές έρευνες του «Διεθνούς Ινστιτούτου  Ιμαλάϊων», για την επιστήμη και τη φιλοσοφία της γιόγκα στις ΗΠΑ, η ζωτική ικανότητα των πνευμόνων ύστερα από εξάσκηση έξι μηνών, αυξήθηκε  από 3.729 κ. εκατοστά σε 4.615. Το μυστικό είναι ακίνδυνο, απλό και  ευκολονόητο. Ονομάζεται πλήρης αναπνοή και περιλαμβάνει τεχνικές της κοιλιακής ή διαφραγματικής αναπνοής, της πλευρικής και της θωρακικής.

Πλήρης μυϊκός έλεγχος και ενδυνάμωση

Οι άσανες (σωματικές ασκήσεις), είναι δυναμικές και στατικές και προάγουν τη μυϊκή ενδυνάμωση, με το βάρος και τη συμμετοχή ολόκληρου του σώματος, ενώ παράλληλα αποφορτίζουν τη σπονδυλική στήλη.

Μείωση των τραυματισμών στα ισχία, τα γόνατα και τους αστραγάλους που ταλαιπωρούν τους αθλητές του ποδοσφαίρου, αφού οι αρθρώσεις είναι κατά πολύ πιο ευλύγιστες.

Kατά την εκτέλεση κάθε είδους άσκησης, είναι αυτονόητο, ότι στόχος των κινήσεων και των στάσεων, αφορά στη σωστή οργάνωση του μυοσκελετικού συστήματος, ειδάλλως οι σύνδεσμοι θα φθαρούν. Βέβαια ένας υγιής και ευλύγιστος ασκούμενος, μπορεί να μη συναντήσει νωρίς προβλήματα, χωρίς ιδιαίτερη προσοχή. Ο δύσκαμπτος αθλητής ή κάποιος με ήδη επιβαρυμένους συνδέσμους , μπορεί πολύ γρήγορα να παραπονεθεί για το μυοσκελετικό του σύστημα και εύκολα να τραυματιστεί. Η ευλυγισία των αρθρώσεων, προάγεται μέσω των πρακτικών της γιόγκα στο μέγιστο σημείο της,  γεγονός που  οδηγεί σε κίνηση με περισσότερη άνεση, μικρότερη καταπόνηση και λιγότερους τραυματισμούς

Βελτίωση ισορροπίας και κιναισθητικής επίγνωσης

Το ποδόσφαιρο απαιτεί ταχύτητα και συγκέντρωση και το σώμα καλείται να κινείται με άνεση, προς όποια κατεύθυνση σε δευτερόλεπτα. Ο χρόνος ανταπόκρισης στην επιθυμητή κίνηση, είναι μεγαλύτερος αν το σώμα είναι εκτός ισορροπίας. Εδώ μέσω των τεχνικών της γιόγκα, επιτυγχάνεται έλεγχος του κέντρου του αθλητή σε μικρό χρονικό διάστημα. Έτσι το σώμα κινείται με ισορροπία, αλλά και σαν ένα ολοκληρωμένο σύνολο, που έχει επίγνωση για το χώρο γύρω του.

Απελευθέρωση του σωματικού, πνευματικού και συναισθηματικού άγχους και  αυξημένη αυτοπεποίθηση

Το παιχνίδι δεν είναι μόνο σωματικό, αλλά και διανοητικό. Η βαθιά χαλάρωση, η θετική προβολή, ο οραματισμός και ο διαλογισμός βοηθούν σε έναν ήρεμο και ξεκάθαρο νου.



Η κ. Εύη Ανδρέου σπούδασε στο Τμήμα Επιστήμης Φυσικής Αγωγής και Αθλητισμού. Εργάστηκε ως προπονήτρια κολύμβησης, γυμνάστρια θεραπευτικής αγωγής σε κέντρα αποθεραπείας και αποκατάστασης, ασχολήθηκε ιδιαίτερα με το personal training, τελείωσε τη GR.A.F.T.S και δούλεψε  για χρόνια ως aerobic instructor. Αποφοίτησε από τη σχολή δασκάλων Hatha Yoga «ο Διδάσκαλος Χείρων», υπό την επίβλεψη του Ανδρέα Προβελέγγιου, του Robert Najemy και της International Yoga Teachers Association. Παρακολούθησε σεμινάρια με σπουδαίους δασκάλους και ξεκίνησε τη διδασκαλία της σε ομαδικά και ατομικά προγράμματα. Μελέτησε τη Raja Yoga και απέκτησε πιστοποίηση διδακτικής επάρκειας σε αυτή. Αργότερα έλαβε εξειδίκευση στη yoga για παιδιά με τη Florence Lalanne. Kάπου ανάμεσα σε όλα αυτά ξεκίνησε πρακτικές στην Ashtanga Yoga η οποία και την συνεπήρε. Σήμερα είναι ιδρυτικό μέλος του Συλλόγου Ελλήνων Επιστημόνων Εκπαιδευτών Χάθα Γιόγκα, διδάσκει, παράλληλα μαθητεύει και χαμογελά.

Το football-academies.gr προσέγγισε την κ. Εύη Ανδρέου με την οποία είχαμε μια ευχάριστη συνομιλία ωρών. Γοητευτήκαμε από την βαθιά της γνώση και την πίστη της στην μεγάλη βοήθεια που μπορεί να προσφέρει η γιόγκα, στον ποδοσφαιριστή, τον αθλητή και στον άνθρωπο γενικότερα. Πειστήκαμε, με τα επιστημονικά επιχειρήματα που μας παρέθεσε, ότι τα ωφελήματα είναι πολλά και σημαντικά για έναν ποδοσφαιριστή.

Ψάχνοντας το θέμα διαπιστώσαμε, ότι πολλοί σπουδαίοι και γνωστοί ποδοσφαιριστές, κάνουν γιόγκα. Ένας από αυτούς είναι ο Ράιαν Γκίγκς της Μάντζεστερ Γιουνάιτεντ. Δείτε παρακάτω τι δήλωσε ο Εβρά για τον Γκίγκς

Εβρά: «Μυστικό του Γκιγκς η...γιόγκα»

Οι καταπληκτικές εμφανίσεις του Ράιαν Γκιγκς με τη φανέλα της Μάντσεστερ Γιουνάιτεντ έχουν προκαλέσει τον θαυμασμό του Πατρίς Εβρά. Ο αμυντικός των «κόκκινων διάβολων» σχολίασε με διθυραμβικά σχόλια της εμφανίσεις του Ουαλού άσου αποκαλύπτοντας μάλιστα ένα μυστικό όπλο του Γκιγκς.

«Είναι πραγματικά απίστευτος. Πρόκειται για έναν 37χρονο με αντοχές 25χρονου. Με τις εμφανίσεις του καταρρίπτει τη λογική» δήλωσε ο Εβρά και συνέχισε: «Ωστόσο πρέπει να σταματήσει να μιλάει συνεχώς για τη γιόγκα. Καταλαβαίνω ότι τον βοηθάει πάρα πολύ και του δίνει απίστευτη αντοχή. Μάλιστα σκέφτομαι να ξεκινήσω κι εγώ. Μας λέει ότι με τη γιόγκα τρέχει πιο γρήγορα και συμφωνώ απόλυτα. Τρέχει περισσότερο απ’ όλους μας και είναι καθοριστικός. Έχω μείνει άφωνος», δήλωσε ο Εβρά μετά τη νίκη με 0-2 κόντρα στη Σάλκε. Πηγή: www.england365.gr

Ο Ράιαν Γκιγκς μιλά για την γιόγκα σε βίντεο που ακολουθεί, δηλώνει υπέρμαχος της γιόγκα και μας αποκαλύπτει, πόσο πολύ τον βοήθησε στη ενδυνάμωση, την ευλυγισία, στην αποφυγή των τραυματισμών, στο να νιώθει υγιής και να μην χάνει αγώνες. Έχει συστήσει τη γιόγκα σε συμπαίκτες και φίλους και στη γιόγκα οφείλει το ότι είναι 37 χρονών (γεννήθηκε 29/11/1973) και παίζει ακόμα στη Manchester United.

Δείτε το πρώτο βίντεο με τον Ράιαν Γκιγκς να κάνει γιόγκα και να αποκαλύπτει πόσο τον βοήθησε ως ποδοσφαιριστή.