name: YogaMarga
markdown: redcarpet
pygments: true

# Prettier URL
permalink: /:title/

# We are adding this below:
source: ./src
destination: ./src_tmp

en:
    landing-page:
        title: 'Unlimited Invoicing'
el:
    landing-page:
        title: 'Απεριόριστη Τιμολόγηση'


t:
    el:
        HOME:  "Αρχική"
        CLASSES: "Μαθήματα"
        EVENTS: "Εκδηλώσεις"
        CONTACT: "Επικοινωνία"
        TEACHERS: "Δάσκαλοι"
    en:
        HOME:  "Home"
        CLASSES: "Classes"
        EVENTS: "Events"
        CONTACT: "Contact"
        TEACHERS: "Teachers"





